### ISSUE TITLE
Guide needs a title and a preface

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/open-org-distributed-work-guide#1]
That's as good a First Issue as I can imagine!

When I created the project materials and repository, I used the working title *The Open Organization Guide to Distributed Teamwork* ("guide" because it fits nicely alongside other resources we curate, like the *Guide to IT Culture Change* and the *Guide for Educators*). But that needn't be the final title if it's not the best one.

Let's use this issue to discuss guide titles as the resource takes shape.

## Title Ideas
- The Open Organization Guide to Distributed Teamwork
- The Open Organization Guide for Distributed Teams
- The Open Organization Guide to Remote Work
- The Open Organization Guide to Succeeding at a Distance
-  People power
- Empowering people
- Human at a Distance*
- Community is Community
- Humans Scrolling
- Distantly Social
- Social at a Distance
- Trust without Body Language
- There is no offline for people*
- Building Brains
- Connecting a Distributed Work Community

## Subtitle ideas
- The Open Organization Guide to Distributed Teamwork
- Harnessing the power of technology to building healthy teams and communities
- Staying Connected When Everyone is Connected
- How to Work Together While Apart

## Sample combinations
- The Open Organization Guide to Distributed Teamwork:
- Never Remote: The Open Organization Guide to Distributed Teamwork
- No Offline for People: The Open Organization Guide to Distributed Teamwork
- The Open Organization Guide to Distributed Teamwork: How to Work Together While Apart
- The Open Organization Guide to Distributed Teamwork: Staying Connected When Everyone is Connected

**Comment by LauraHilliger** [comment]
Given the content, I feel like this is multimedia. Videos about how to do different types of online, participatory exercises, synch or asyc, a sound interview for accountability...would be fun to miz it up. Then we can have all the written bits in the Guide and on it's download page, something like "Source Collection for Distributed People"

**Comment by semioticrobotic** [comment]
Interesting idea! I can see this working well—perhaps start with a downloadable guide as a sort of "minimum viable product" (I'm thinking our "v1.0" will be something like six or seven collected pieces, to get us started), then build out a complimentary page online where readers can go to access learning materials, like a few video explainers, a podcast, a tutorial or two, etc. Could be really cool.

Multimedia is largely outside my particular skill set, so I'll defer to other contributors for advice on feasibility, best ways to proceed, etc. Would be very cool to see this happen!

**Comment by semioticrobotic** [comment]
During a [project sprint](https://github.com/orgs/open-organization/teams/guide-to-distributed-teamwork/discussions/1), participants discussed a general affinity for the title _The Open Organization Guide to Distributed Teamwork_ and discussed keeping it around. The question is whether it should be the book's title (the more conventional approach, given our series' history) or the subtitle (the unconventional approach).

Editor @semioticrobotic mentioned he initially suggested the title because it fits nicely among our ongoing series:

- _The Open Organization Guide for Educators: Transformative Teaching and Learning for a Rapidly Changing World_
- _The Open Organization Guide to IT Culture Change: Open Principles and Practices for a More Innovative IT Department_
- _The Open Organization Guide to Distributed Teamwork: A Subtitle That Specifies The Book's Intent for Readers_
- ... and so on

Contributor @funnelfiasco suggested perhaps a shorter, punchier primary title, then using "The Open Organization Guide to Distributed Teamwork" as a subtitle—something like:

- _THREE WORD TITLE: The Open Organization Guide to Distributed Teamwork_

The conversation continues! All contributors welcome to chime in.

**Comment by semioticrobotic** [comment]
Had some writing time this morning, so built on the already great work of @LauraHilliger in pushing an [updated preface](https://github.com/open-organization/open-org-distributed-work-guide/blob/master/00_hilliger-behrenshausen-preface.md). Feedback (always) welcome.

**Comment by LauraHilliger** [comment]
Oh it's epic. Inspiring. I literally had to go back to the first draft because I thought "did I contribute any of that"? Turns out we work well together 🥇  Really nice edits!!

**Comment by semioticrobotic** [comment]
> Oh it's epic. Inspiring. I literally had to go back to the first draft because I thought "did I contribute any of that"? Turns out we work well together. Really nice edits!!

Heck yes you did! Thanks to you, I just needed to add a few thoughts up front (just some additional context I'd been noodling on). You had the rest already taken care of. That was a huge boon over the weekend (and prompted me to go downstairs, shaking my head in awe of your brilliance, as I explained the work to my partner).

**Comment by LauraHilliger** [comment]
Stop it. My head is blowing up!

**Comment by LauraHilliger** [comment]
@semioticrobotic and I chatted about future titling norms and wanted to give @funnelfiasco 's suggestion a go as we feel it's a nice way to open up the creativeness of our community. Plus with the new brand, it's a good time to play around with new norms and see where they take us.

After reviewing the preface and TOC, then walking around a bit thinking on this, I decided the word people or human or community needs to be in the title (i diverged from that halfway down) and that it needs to evoke relationshipy, connectyness...here's 10 not-thought out ideas:

1) People power
2) Empowering people
3) Human at a Distance*
4) Community is Community
5) Humans Scrolling
6) Distantly Social
7) Social at a Distance
8) Trust without Body Language
9) There is no offline for people*
10) Building Brains

subtitle ➡️ The Open Organization Guide to Distributed Teamwork

I actually like the 2 with the stars, the rest are to get the ball rolling.

**Comment by funnelfiasco** [comment]
Ooh, I really like "Human at a Distance". How about "Connecting a Distributed Work Community"?

**Comment by semioticrobotic** [comment]
A big :heavy_plus_sign: for *Human at a Distance*. I will also add a few of my own here and begin updating the top post in this thread :point_up: to collect some of the most desirable combinations (also to record @funnelfiasco's nice suggestion).

- Never Remote: The Open Organization Guide to Distributed Teamwork
- The Open Organization Guide to Distributed Teamwork: How to Work Together While Apart
- The Open Organization Guide to Distributed Teamwork: Staying Connected When Everyone is Connected

**Comment by guywmartin** [comment]
Nothing significant to add here, other than a huge hooray for Human at a Distance!  What a fantastic title for this book!  Can't wait to see it come out and super happy to have been a teeny, tiny part of it. :)

**Comment by semioticrobotic** [comment]
Thanks so much for the input, @guywmartin! Sounds like strong preference for:

*Human at a Distance: The Open Organization Guide to Distributed Teamwork*

**Comment by LauraHilliger** [comment]
Human at a Distance 
An Open Organization Guide to Distributed Teamwork

(no colon, with indefinite article, @semioticrobotic see [cover issue 39](https://github.com/open-organization/open-org-distributed-work-guide/issues/39))?

Are we agreed? Can we close this ticket?

**Comment by semioticrobotic** [comment]
Yes, sorry! Looks like the preference is "**An** Open Organization Guide..." Happy to go with that, of course.

**Comment by semioticrobotic** [comment]
Happy to close this and consider this decided, given the strong preferences in favor. Thanks, all! And kudos @LauraHilliger for the great title.
