### ISSUE TITLE
Add a chapter on the benefits of transparent issue tracking

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/open-org-distributed-work-guide#11]
Remote teams benefit from shared, transparent issue tracking systems and practices—something with which open communities have particular experience. Long ago, we published work from @chadwhitacre on [this very topic](https://opensource.com/open-organization/17/2/tracking-issues-publicly) and I'd very much love if he'd consider including something like this in the guide.

**Comment by chadwhitacre** [comment]
Hah! So meta! :D

Yes, I would love to see the piece on issue tracking continue to provide value in this unique environment we find ourselves in. Thanks for thinking of me/it!

**Comment by semioticrobotic** [comment]
Woo hoo!

Great to see you again, @chadwhitacre. Though I'm a bit disappointed by the lack of flamenco dancing emojis in your response.

I'll get to work inputting the piece into this repo and you'll have an opportunity to review and revise if you wish.

**Comment by semioticrobotic** [comment]
I've merged this, @chadwhitacre, and wanted to note that here in case you [wanted to take a look](https://github.com/open-organization/open-org-distributed-work-guide/blob/master/00_whitacre-tracking-issues-publicly.md). Could you offer an updated bio statement?

**Comment by chadwhitacre** [comment]
Moving to a PR in #20. 💃
