### ISSUE TITLE
Add an introductory chapter

### ISSUE THREAD

**Issue by funnelfiasco** [open-organization/open-org-distributed-work-guide#12]
Why even have distributed work?

**Comment by funnelfiasco** [comment]
Stealing heavily from my previous [OpenOrg article](https://opensource.com/open-organization/19/1/remote-work-inclusivity) would fit well here, as @semioticrobotic and I discussed in chat.

**Comment by semioticrobotic** [comment]
Love it. I've earmarked a place in the table of contents for this, and you've got it.

**Comment by semioticrobotic** [comment]
Thanks for using the one-sentence-per-line convention. I did not think Markdown (and my typesetting toolchain) would cooperate with this (AsciiDoc does, and we use it—and the convention—in the Open Source Way project), but I tested it and it does! I will likely update all working drafts to use this convention.

**Comment by semioticrobotic** [comment]
Made [a few additional suggestions](https://github.com/open-organization/open-org-distributed-work-guide/commit/4b455f3578c70d9530f392d71b27cccdb374f619#diff-c9bb93f11ac485ea2e0c3ee266f2cfb3) on the introduction this afternoon, @funnelfiasco. I also left one inline comment for you. Take a look and see what you think.

**Comment by funnelfiasco** [comment]
It'd be helpful to put the editorial changes and the file rename in separate commits so I can look at the diff and see what you changed. I'll download the raw versions and compare them. 

Also, GitHub supports adding comments to lines in the web UI, so that might be an easier feedback approach than adding comments in the file.

**Comment by semioticrobotic** [comment]
> It'd be helpful to put the editorial changes and the file rename in separate commits so I can look at the diff and see what you changed. I'll download the raw versions and compare them.

 Oh, crap. You're totally right. I had not considered that consequence of renaming the file (not the inconsequential action I assumed it'd be!). Sorry to make the extra work for you.

> Also, GitHub supports adding comments to lines in the web UI, so that might be an easier feedback approach than adding comments in the file.

I remembered that just a second too late! But will surely use it next time. Thanks for your patience with a n00b like me. :smiley:

**Comment by funnelfiasco** [comment]
> Oh, crap. You're totally right. I had not considered that consequence of renaming the file (not the inconsequential action I assumed it'd be!). Sorry to make the extra work for you.

I'm the last person who can complain about using git to make someone else's life harder. ;-)

The edits look good to me. 

For line 66, what I was going for is that the suggestion is about adding new people to the community, but also about allowing the people you have to be more productive. It may be that we're not really talking about adding new people, in which case, I think I know how I want to edit that line. If we are, then I'm open to your suggestions on how to make this more clear.
> > Also, GitHub supports adding comments to lines in the web UI, so that might be an easier feedback approach than adding comments in the file.
> 
> I remembered that just a second too late! But will surely use it next time. Thanks for your patience with a n00b like me.

**Comment by semioticrobotic** [comment]
> For line 66, what I was going for is that the suggestion is about adding new people to the community, but also about allowing the people you have to be more productive. It may be that we're not really talking about adding new people, in which case, I think I know how I want to edit that line. If we are, then I'm open to your suggestions on how to make this more clear.

I see. Thanks. I do believe it's the latter. Let me float some comments in the diff and we can go from there (good excuse to test that workflow).

**Comment by semioticrobotic** [comment]
Ah! Okay. I think I did this in [the wrong thread](https://github.com/open-organization/open-org-distributed-work-guide/pull/26). My mistake. :smile: 

Are you able to [view the marginalia now](https://github.com/open-organization/open-org-distributed-work-guide/pull/26)?

**Comment by semioticrobotic** [comment]
[Merged](https://github.com/open-organization/open-org-distributed-work-guide/pull/26)! Thanks very much, @funnelfiasco.

**Comment by semioticrobotic** [comment]
Sorry to bug you again, @funnelfiasco. When you have a sec, could you add your preferred bio statement to the conclusion of the introduction? I'd overlooked that while editing. No need to reopen this, though (unless you want). Thanks.
