### ISSUE TITLE
Add a chapter on Communication practices typical of high-performing remote teams

### ISSUE THREAD

**Issue by jimmysjolund** [open-organization/open-org-distributed-work-guide#13]
Perhaps my previous chapter on Visualizing work updated with my drafts on remote collaboration and phsycological safety could fit into this heading?

**Comment by semioticrobotic** [comment]
I'd really love to see this, @jimmysjolund. When you have a free moment (ha!), would you be able to whip up a brief, general outline of the article and share it so we can get a more concrete sense of what you're imagining?

**Comment by semioticrobotic** [comment]
@jimmysjolund I get the sense (from our work in another repo), that this is essentially finished. What do you think? Ready to open a PR (or should I)?
