### ISSUE TITLE
Add a chapter on self-organizing teams

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/open-org-distributed-work-guide#15]
Community contributor @alexismonville has graciously agreed to reprise his work on [self-organization and open management](https://opensource.com/open-organization/18/8/self-organizing-team-management) for the guide. From the work:

> "Self-organization" and "management" aren't mutually exclusive. But we'll need to rethink the role of the manager if we're planning to build adaptable teams.

**Comment by semioticrobotic** [comment]
I've now pushed @alexismonville initial draft [to the project repository](https://github.com/open-organization/open-org-distributed-work-guide/commit/0ecbf4eeb31731316ebac7d089443a5196429ccb). The author will propose small revisions that better situate the guide in the specific context of distributed teamwork (won't be difficult!).

**Comment by semioticrobotic** [comment]
I made [a few additional copy edits](https://github.com/open-organization/open-org-distributed-work-guide/commit/07a9a792caed2d0fd247c68db8f051c643fa2a0a), @alexismonville. What do you think?

**Comment by alexismonville** [comment]
@semioticrobotic all looks perfect to me! 
Great work!

**Comment by semioticrobotic** [comment]
Excellent! Thanks, @alexismonville. I'll move us along to production. Really appreciate your partnership on this!
