### ISSUE TITLE
Add a chapter on lessons learned from one year on a remote team

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/open-org-distributed-work-guide#23]
New contributor @anupama23-tec just finished a draft on this topic and we're working on submitting it to the guide!

**Comment by semioticrobotic** [comment]
Okay, @anupama23-tec: I've typeset this an merged it with the main branch. It's [ready for your review](https://github.com/open-organization/open-org-distributed-work-guide/blob/master/00_jha-one-year-on-distributed-team.md). I'd suggest just giving it a quick look to help ensure that nothing was garbled in the text conversion.

If everything looks okay to you, we'll go ahead and move this along. Thanks for writing it!

**Comment by anupama23-tec** [comment]
Thank you @semioticrobotic, I have reviewed the article and I'm pleased with everything in it. Let's move ahead with the next step.

**Comment by semioticrobotic** [comment]
Great, @anupama23-tec! I'll take care of next steps, which involve getting your great chapter into our "preview release" of the guide, due by the end of the month. Now that you're on the project team, you can follow all project conversation [on our team page](https://github.com/orgs/open-organization/teams/guide-to-distributed-teamwork) (I'll also be ensuring that you're all looped in as we move forward). Thanks for your great work.

**Comment by anupama23-tec** [comment]
Sounds great! Thank you so much, looking forward to it @semioticrobotic.
