### ISSUE TITLE
Version 0.90 must be proofed for release

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/open-org-distributed-work-guide#28]
Our "preview release" of the guide is [now in the project repository](https://github.com/open-organization/open-org-distributed-work-guide/tree/master/0.90).

But that release needs to be more thoroughly vetted and proofed before we release it. So let's use this space to coordinate that process.

Please download a copy of the guide and take it for a spin. Notice something odd? Either comment in this issue and make note of it, or go right ahead and fix it yourself (just don't forget to push your changes!).

## Running list of corrections

- [x] Back matter is missing
- [x] Open Organization Definition must be reproduced in Appendix
- [x] Spacing of section headers in table of contents seems wrong
- [x] Some contributors are missing bio statements in "About the Contributors"
- [x] URLs on copyright page should be tidied up

**Comment by amatlack** [comment]
~@semioticrobotic page 54, "don't getoverlooked" needs a space there~

**Ed: Got it. Thanks!**

**Comment by semioticrobotic** [comment]
Paging @MaineC: When you have a moment, could you [add your bio statement](https://github.com/open-organization/open-org-distributed-work-guide/blob/master/contributors.md) to `contributors.md`?

**Comment by funnelfiasco** [comment]
It's weird to have URLs in the body and also in the footnotes. In the Copyright section, would it be better to have something like

    Alice Openorg's "Here's why being cool is totally rad" was originally published on [Example.com](https://example.com/alice/being-cool).

**Comment by semioticrobotic** [comment]
Yeah, you're right @funnelfiasco. That should be an easy change to make, and I can update that today (I think). I will likely just change the text to something like:

> The following chapters originally appeared at Opensource.com:

... and then list titles and authors with footnotes to their respective URLs. This is to maintain compliance with the Creative Commons license (apropos the other thread you initiated today, which I will also address shortly!).

**Ed: Done!**

**Comment by semioticrobotic** [comment]
Made lots of changes and additions today. My thanks to everyone for their careful reads and responsiveness to requests. I think we're very close.

If you see anything else that needs fixing in the newly pushed proofs, please let me know.

**Comment by alexismonville** [comment]
I went through it today, and it looked great to me!

**Comment by semioticrobotic** [comment]
Thanks so much for your work in doing that, @alexismonville. Appreciated!

Looks like we're nearing time for v0.90 release. I'll begin making preparations.
