### ISSUE TITLE
Add a chapter on developing a culture of transparency

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/open-org-distributed-work-guide#3]
The guide could use a chapter on the nuances of transparency in remote work.

**Comment by semioticrobotic** [comment]
Contributor @guywmartin has graciously allowed us to reprint [his previous work](https://opensource.com/open-organization/17/12/chat-platform-default-to-open) on this subject, and I'm working on typesetting it straight away.

**Comment by semioticrobotic** [comment]
This is [now merged and available for review](https://github.com/open-organization/open-org-distributed-work-guide/blob/master/00_martin-chat-transparency.md) if you'd like, @guywmartin. I did perform a few basic edits to update references to your (former) employer. Additional edits welcome (but certainly not required).

**Comment by guywmartin** [comment]
Thanks @semioticrobotic - this looks good - and I appreciate you switching things around to reference the fact that it's my former role now.  I'm good with this in its current form now.

**Comment by semioticrobotic** [comment]
Great! Thanks so much, @guywmartin. Delighted to be able to include this!
