### ISSUE TITLE
Add a chapter on conducting effective community calls

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/open-org-distributed-work-guide#4]
Open source projects seem particularly adept at fostering community remotely. What can remote teams learn from their habits and practices?

**Comment by LauraHilliger** [comment]
co-op has been working on a successful virtual meetings email course, I find that good meetings = fostering community by default. Perhaps we can rip and remix:

https://learnwith.weareopen.coop/

**Comment by semioticrobotic** [comment]
Would love to see that, @LauraHilliger. If you don't mind, I'll assign this chapter to you so I remember to track this discussion and we can work toward bringing a brief version of your tutorial to life as a chapter in the guide. Super great.

**Comment by LauraHilliger** [comment]
Hm. So for this title I am changing my mind and wondering if we've already included my "most useful post ever" (https://opensource.com/open-organization/16/1/community-calls-will-increase-participation-your-open-organization) in another book...It fits here perfectly. 

The  https://learnwith.weareopen.coop could just be a "Learn more" link on the book's snazzy webpage

**Comment by semioticrobotic** [comment]
You know, I thought we'd reproduced this piece in the _Field Guide_, but I'm not seeing it there after all. Huh.

So, yeah, happy to reprint this here if you'd like. I'll go ahead and get it into this repository for you to review/update/hack on as you see fit.

**Comment by semioticrobotic** [comment]
Okay. This is now [merged and ready](https://github.com/open-organization/open-org-distributed-work-guide/commit/06b2b1b280dfb329414c2206e4997c625c922c0e).

**Comment by semioticrobotic** [comment]
Love it. Thanks, @LauraHilliger. Anything more to add or address before we wrap?

**Comment by semioticrobotic** [comment]
Reopening this because I realized the chapter doesn't include @LauraHilliger's bio statement.

**Comment by LauraHilliger** [comment]
> Reopening this because I realized the chapter doesn't include @LauraHilliger's bio statement.

I don't understand where this should go? I clicked on the other chapters, and didn't see bios anywhere....please advise?

**Comment by semioticrobotic** [comment]
Sorry! I should have been more specific.

The bio goes at the end of each chapter. It's just a two- or three-sentence blurb about you. :smile: 

For example, see [Alexis'](https://github.com/open-organization/open-org-distributed-work-guide/blob/master/00_monville-self-organization-management.md) or [Chad's](https://github.com/open-organization/open-org-distributed-work-guide/blob/master/00_sansing-building-movement-from-home.md).

**Comment by semioticrobotic** [comment]
You know what, I'm game to try something different this time 'round. Since we're working differently, I'm proposing a "Contributors" section in the book's back matter that collects all the bio statements in one place (previously, the statements appeared at the end of every chapter). I think this:

1. Makes the book look cleaner in production, and
2. Makes managing bios easier (since they're all in one place).

So you can just go ahead and [fill yours out](https://github.com/open-organization/open-org-distributed-work-guide/blob/master/contributors.md) in the ``contributors.md`` file, as @funnelfiasco and I also need to do!
