### ISSUE TITLE
Require updated contributor bios

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/open-org-distributed-work-guide#40]
As we [prepare for the launch of v1.0](https://github.com/open-organization/open-org-distributed-work-guide/projects/1), we'll want to ensure all contributor bio statements are current.

Newly added authors @amatlack and @simzacks should [add their bio statements](https://github.com/open-organization/open-org-distributed-work-guide/blob/master/contributors.md) to ``contributors.md`` (or send something to me, and I will update), and returning authors should please confirm their bios read as they'd prefer.

**Comment by amatlack** [comment]
@semioticrobotic I've added my bio to the file :)

**Comment by semioticrobotic** [comment]
Just added @simzacks and will review the entire list soon to ensure we haven't missed anyone.

**Comment by semioticrobotic** [comment]
Everything updated for v1.0! Thanks, everyone.
