### ISSUE TITLE
Galley proofs of v1.0 need final review

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/open-org-distributed-work-guide#42]
I've just pushed galley proofs of v1.0! You'll find them here:

https://github.com/open-organization/open-org-distributed-work-guide/tree/master/books

They could use a once-over before we ship. I will be scrutinizing, and ask any/all interested contributors to do the same. Please use this space to note issues you find, and I'll assume responsibility for fixing them.

Things to note:

- Typographical inconsistencies 
- Hyperlinks that haven't converted to footnotes
- Minor spelling or grammatical errors
- Incorrect page numbers

Essentially, anything is fair game as we polish for a release.

**Comment by semioticrobotic** [comment]
- [x] Capitalization of "Additional [R]esources" is incorrect on page 122.
- [x] Pagination around "Appendix" separator could use work

**Comment by LauraHilliger** [comment]
@semioticrobotic Ok, skimming through the PDF. A bit nitpicky, so do feel free to ignore. Just things that caught my eye:

- [x] "Dee Hock, the innovative founder of Visa, said it well" | Hanging indent | page 23 (in the pdf)
- [ ] ``wontfix`` top margin at the beginning of articles (for example - pages 38, 54, 63) looks too big? 
- [x] Not sure I should point out orphans in headlines, but there is one on page 22 and another on page 75

didn't see anything else major, but also only spent a few minutes. It's looking awesome!!

**Comment by semioticrobotic** [comment]
*Thank you!* Pick those nits. I turned your bullets into check boxes so I can track as a fix. Great finds.

**Comment by semioticrobotic** [comment]
> top margin at the beginning of articles (for example - pages 38, 54, 63) looks too big?

This one is intentional, in keeping with the formatting of all our other books. We use a generous top margin at the start of chapters to visually offset them. It's more appropriate in the printed volumes than the digital ones, but I am inclined to flag this as ``wontfix``, at least for now. :smile:

**Comment by semioticrobotic** [comment]
> Not sure I should point out orphans in headlines, but there is one on page 22 and another on page 75

You should definitely point this out! Unfortunately, two of the quick-fix solutions I attempted did not do the trick, and I think further exploration will involve going through the book template and fixing this at a structural level. So for now, I think perhaps it's best to save for v1.1.

**Edit:** Fixed this with an "editorial hack"—that is, re-writing the title!
