### ISSUE TITLE
Duplicate word in introduction

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/open-org-distributed-work-guide#43]
Eagle-eyed reader @RonMcFarland says notes a duplicate word in line 85 of @funnelfiasco's introduction:

> This is [where where] the organization truly begins reaping the benefits of remote work.

**Comment by gaurav24072002** [comment]
I have proposed the changes by removing the duplicate word 'where'
thank's for giving me a chance..

**Comment by semioticrobotic** [comment]
Thanks! Everything looked great, and I merged your pull request.
