### ISSUE TITLE
Migrate or close the Project (classic)?

### ISSUE THREAD

**Issue by jimmysjolund** [open-organization/open-org-distributed-work-guide#48]
As the Project used in this repo will be decommissioned in August, we should decide to migrate or close the project (if not needed any longer).

> Projects (classic) will be sunset on August 23, 2024

Ping @semioticrobotic

**Comment by semioticrobotic** [comment]
Thanks for noting this, @jimmysjolund. Since this edition of book is finished, i think we're safe to close.

**Comment by jimmysjolund** [comment]
I closed the project, but not all the open issues.
