### ISSUE TITLE
Add a chapter on considerations for selecting communication tools

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/open-org-distributed-work-guide#7]
This seems like a natural fit for the guide: a chapter on communication habits and practices typical of successful open communities and organizations. How does working in a distributed fashion require people to think differently about their communication styles and preferences?

**Comment by funnelfiasco** [comment]
I wrote a [blog post](https://funnelfiasco.com/blog/2019/01/07/picking-communication-tools-for-your-community/) a while back that would fit well into this section as a starting point. There's some stuff in my giant [WFH post](https://funnelfiasco.com/blog/2020/04/07/working-from-home-my-advice/) that would fit, too.

**Comment by semioticrobotic** [comment]
I really like the "considerations" material you link here, especially the "questions-to-ask-yourself" nature of it. I wonder if you could write a slightly more robust introduction that puts the questions and considerations more squarely in the context of distributed teamwork—that is, explain a bit more deeply why these considerations *are* considerations in the context of remote work (what makes them important, what effects they have, etc.).

I should also note that I probably wrote this issue a little hastily, as if we could *possibly* cover "communication practices" in something like a few pages. So I can evolve this issue as your proposal matures, and then open some new issues for additional items on communication (for example, while you're focused here primarily on tools, I think we could still use something specifically on practices).

**Comment by funnelfiasco** [comment]
> I should also note that I probably wrote this issue a little hastily, as if we could possibly cover "communication practices" in something like a few pages. So I can evolve this issue as your proposal matures, and then open some new issues for additional items on communication (for example, while you're focused here primarily on tools, I think we could still use something specifically on practices).

For sure. The yet unwritten parts cover etiquette and communication norms. I think that would flow pretty well from this starting point. It might absorb #8 or complement it. I guess we'll see what it looks like as words start hitting the page.

**Comment by semioticrobotic** [comment]
All sounds great, @funnelfiasco. Looking forward to working with you on this (and learning from you!).

**Comment by funnelfiasco** [comment]
Anyone have strong opinions about bridging platforms (e.g. Telegram <-> IRC)? The more time passes, the more strongly I oppose this, but I don't necessarily want to give spicy takes in a collective work.

**Comment by semioticrobotic** [comment]
I'm not savvy enough to know whether this is gauche these days, but I'd say that advocating whatever helps mainstream audiences best succeed without much overhead is an acceptable position for this collection. Others may feel more strongly.

**Comment by semioticrobotic** [comment]
I would really love to call this one something like "What to Expect when You're Connecting" or "What to Select when You're Connecting."
