### ISSUE TITLE
Add a chapter on building cohesive remote teams

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/open-org-distributed-work-guide#8]
Open organizations and communities often benefit from explicit social contracts and records of conventional social norms. We might consider some material on establishing and maintaining social norms and contracts transparently and collaboratively.

**Comment by simzacks** [comment]
I was thinking that this chapter would be a good fit for building cohesive remote teams, using virtual coffee breaks, online activities and other interpersonal communication that are not directly related to work.

**Comment by semioticrobotic** [comment]
I like the idea, @simzacks, and very much welcome a chapter on this topic. If you'd like to get community feedback as you outline and brainstorm, feel free to use this space. I'll update the issue title to reflect your goals.

When you have something substantive for review, we can review it in a more formal pull request.

**Comment by simzacks** [comment]
I started writing instead of outlining (oops), and just made the PR

**Comment by semioticrobotic** [comment]
On it! Thanks so much, @simzacks. More soon.
